export enum ErrorCode {
    UNDEFINED = 0,

    // Network
    ON_CREATE_NETWORK = 101,
    ON_ADD_HOST = 102,
    ON_ADD_SECURITY_GROUP = 103,
    NETWORK_ALREADY_RUNNING = 110,

    // Host
    ON_CREATE_HOST = 201,
    ON_ATTACH_INSTANCE_PROFILE = 202,
    ON_SYNCHRONIZE_HOST = 203,
    ON_CHANGE_HOST_STATE = 204,
    ON_WAIT_FOR = 205,
    ON_GET_IMAGE_ID = 206,
    HOST_ALREADY_RUNNING = 210,

    // Security Group
    ON_CREATE_SECURITY_GROUP = 301,
    ON_DESTROY_SECURITY_GROUP = 302,
    ON_CREATE_RULE = 303,
    ON_SYNCHRONIZE_SECURITY_GROUP = 304,
    ON_GET_DEFAULT_VPC = 305,
    SECURITY_GROUP_DUPLICATE = 306,
    SECURITY_GROUP_ALREADY_RUNNING = 310,
    SECURITY_GROUP_NOT_RUNNING = 311,
    SECURITY_GROUP_RULE_PORT_MISSING = 320,
    SECURITY_GROUP_RULE_SOURCE_MISSING = 321,
    SECURITY_GROUP_RULE_INVALID_PROTOCOL = 322,

}
