export enum Zone {
  US_EAST_1A = 'us-east-1a',
  US_EAST_1B = 'us-east-1b',
  US_EAST_1C = 'us-east-1c',
  US_EAST_1E = 'us-east-1e',
  US_WEST_1A = 'us-west-1a',
  US_WEST_1B = 'us-west-1b',
  US_WEST_2A = 'us-west-2a',
  US_WEST_2B = 'us-west-2b',
  US_WEST_2C = 'us-west-2c',
  EU_WEST_1A = 'eu-west-1a',
  EU_WEST_1B = 'eu-west-1b',
  EU_WEST_1C = 'eu-west-1c',
  EU_CENTRAL_1A = 'eu-central-1a',
  EU_CENTRAL_1B = 'eu-central-1b',
  AP_SOUTHEAST_1A = 'ap-southeast-1a',
  AP_SOUTHEAST_1B = 'ap-southeast-1b',
  AP_SOUTHEAST_2A = 'ap-southeast-2a',
  AP_SOUTHEAST_2B = 'ap-southeast-2b',
  AP_SOUTHEAST_2C = 'ap-southeast-2c',
  AP_NORTHEAST_1A = 'ap-northeast-1a',
  AP_NORTHEAST_1C = 'ap-northeast-1c',
  SA_EAST_1A = 'sa-east-1a',
  SA_EAST_1B = 'sa-east-1b',
  SA_EAST_1C = 'sa-east-1c',
}
